server:
  port: 9100

eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka2:9000/eureka/,http://${eureka.instance.hostname}:9100/eureka/
  server:
    response-cache-auto-expiration-in-seconds: 1
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        beans: b
        exposure:
          include: '*'