spring:
  profiles:
    active: prod
  application:
    name: ribbonconsumer

server:
  port: 9002
management:
  endpoints:
    web:
      base-path: /hecy


eureka:
  client:
    healthcheck:
      enabled: true