eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka2:9000/eureka/,http://eureka1:9100/eureka/
    fetch-registry: true #获取注册中心服务清单
    registry-fetch-interval-seconds: 10
  instance:
    statusPageUrlPath: http://localhost:9002/actuator/info
    healthCheckUrlPath: http://localhost:9002/actuator/health