eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka2:9000/eureka/,http://eureka1:9100/eureka/
    fetch-registry: true #获取注册中心服务清单
    registry-fetch-interval-seconds: 10
  instance:
    statusPageUrlPath: /hecy/info  # 可以是相对路径  当需要https访问时 也可以配置成绝对路径
    healthCheckUrlPath: /hecy/health


management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: hystrix.stream