server:
  port: 9000

eureka:
  instance:
    hostname: eureka2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/,http://eureka1:9100/eureka/
  server:
    enableSelfPreservation: false
    response-cache-auto-expiration-in-seconds: 180
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        beans: b
        exposure:
          include: '*'