eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka2:9000/eureka/,http://eureka1:9100/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1 #服务续约任务调用间隔时间  心跳
    leaseExpirationDurationInSeconds: 2 # 服务失效时间
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instance-id: ${spring.application.name}:${random.int}
#    hostname: localhost