server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka2:9000/eureka/,http://eureka1:9100/eureka/
    fetch-registry: true #获取注册中心服务清单
    registry-fetch-interval-seconds: 10
spring:
  cloud:
    config:
      server:
        git:
          username: hechangyong
          password: hechangyong1234
          uri: https://github.com/hechangyong/learnspringcloud.git
          search-paths: config-repo
  security:
    user:
      name: hecy
      password: 12345678
