eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    statusPageUrlPath: http://localhost:9001/actuator/info
    healthCheckUrlPath: http://localhost:9001/actuator/health